=== Malmo-Skyttegille-Pistolsektionen/rotation_target/resources/openapi/program.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "program.schema.json",
  "title": "Program",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "description",
    "readonly",
    "series"
  ],
  "properties": {
    "id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "readonly": {
      "type": "boolean"
    },
    "series": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Series"
      }
    }
  },
  "$defs": {
    "Series": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "optional",
        "events"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "optional": {
          "type": "boolean",
          "default": false
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Event"
          }
        }
      }
    },
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "duration"
      ],
      "properties": {
        "duration": {
          "type": "integer",
          "description": "Duration of the event in milliseconds. For example: 1000 = 1.0s, 5000 = 5.0s, 60000 = 60s.",
          "minimum": 0
        },
        "command": {
          "type": "string"
        },
        "audio_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "List of audio IDs associated with the event."
        },
        "target_system": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "List of target system IDs associated with the event. If not specified, all target systems are affected."
        },
        "start": {
          "type": "boolean",
          "description": "Marks this event as the starting event in the series. Only one event per series may have start=true."
        }
      }
    }
  }
}

=== Malmo-Skyttegille-Pistolsektionen/rotation_target/resources/programs/files/60.json
{
  "id": 60,
  "title": "Militär Snabbmatch (Klubbmästerskap)",
  "description": "Provserie 10s, 10s x 2 (+1), 8s x 2 (+1), 6s x 2 (+1)",
  "readonly": true,
  "series": [
    {
      "name": "Provserie 10s",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            50,
            1,
            28
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "10s Serie 1",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            64
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "10s Serie 2",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            65
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Färdigskjutning 1, 10 sekunder",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            84
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "8s Serie 1",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            68
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 8000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "8s Serie 2",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            69
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 8000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Färdigskjutning 1, 8 sekunder",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            86
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 8000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "6s Serie 1",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            72
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 6000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "6s Serie 2",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            73
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 6000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Färdigskjutning 1, 6 sekunder",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            88
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 6000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    }
  ]
}
